version: '3'

services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=snort
      - MYSQL_USER=snort
      - MYSQL_PASSWORD=snort
    volumes:
      - /var/lib/mysql:/var/lib/mysql/
      - /etc/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
