---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./secrets/{{ inventory_hostname }}.yml"
    - "./vars/{{ inventory_hostname }}.yml"
  roles:
    - snort
    - pulledpork
    - bro
  tasks:
