---
- hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
  vars_files:
    - "./secrets/{{ inventory_hostname }}.yml"
    - "./vars/{{ inventory_hostname }}.yml"
  roles:
    - bro
    - snort
    - pulledpork
  tasks:
