---
- name: install conky
  package:
    name: conky
    state: present
  tags: [ 'conky' ]

- name: generate ~/.conkyrc
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ ansible_user }}/.{{ item }}"
  with_items:
    - conkyrc_left
    - conkyrc_right
  tags: [ 'conky' ]
