---
- name: Install pulledpork dependancies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - perl
    # - perl-archive-tar
    - cronie
    - perl-lwp-protocol-https
    - perl-crypt-ssleay
    - perl-switch
  tags: [ "pulledpork" ]

- name: Install pulledpork dependencies from aur
  yaourt:
    name: perl-bytes-random-secure
    user: "{{ ansible_user }}"
  tags: [ "pulledpork" ]

- name: Download pulledpork from github
  git:
    repo: "https://github.com/shirkdog/pulledpork.git"
    dest: "{{ pulledpork.src_dir}}/pulledpork-{{ pulledpork.version }}"
    version: "{{ pulledpork.version }}"
  tags: [ "pulledpork" ]

- name: Copy pulledpork.pl
  copy:
    src: "{{ pulledpork.src_dir}}/pulledpork-{{ pulledpork.version }}/pulledpork.pl"
    dest: "/usr/local/bin/pulledpork.pl"
    owner: root
    group: root
    mode: 0755
  tags: [ "pulledpork" ]

- name: Copy pulledpork conf files
  copy:
    src: "{{ pulledpork.src_dir}}/pulledpork-{{ pulledpork.version }}/etc/{{ item }}"
    dest: "/etc/snort/{{ item }}"
    owner: snort
    group: snort
    mode: 0644
  with_items:
    - disablesid.conf
    - dropsid.conf
    - enablesid.conf
    - modifysid.conf
  tags: [ "pulledpork" ]

- name: Generate /etc/snort/pulledpork.conf
  template:
    src: "pulledpork.conf.j2"
    dest: "/etc/snort/pulledpork.conf"
    owner: snort
    group: snort
    mode: 0644
  notify:
    - update rules

- name: update rules every morning at 9
  cron:
    name: "update rules"
    minute: "0"
    hour: "9"
    job: "/usr/local/bin/pulledpork.pl -c /etc/snort/pulledpork.conf -l"
