---
- name: Install barnyard2 dependancies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - autoconf
    - libtool
  tags: [ "barnyard2" ]

# - name: Install barnyard2 dependencies from aur
#   yaourt:
#     name: libmysqlclient
#     user: "{{ ansible_user }}"
#   tags: [ "barnyard2" ]

- name: generate barnyard2 dir
  file:
    path: /var/log/barnyard2
    state: directory
    owner: snort
    group: snort
    mode: 0755
  tags: [ "barnyard2" ]

- name: generate woldo file
  file:
    path: /var/log/snort/barnyard2.waldo
    state: touch
    owner: snort
    group: snort
    mode: 0755
  tags: [ "barnyard2" ]

- name: Download barnyard2 from github
  git:
    repo: "https://github.com/firnsy/barnyard2"
    dest: "{{ barnyard2.src_dir}}/barnyard2-{{ barnyard2.version }}"
    version: "{{ barnyard2.version }}"
  tags: [ "barnyard2" ]

- name: run autogen.sh
  command: ./autogen.sh
  args:
    chdir: "{{ barnyard2.src_dir}}/barnyard2-{{ barnyard2.version }}"
    creates: "{{ barnyard2.src_dir}}/barnyard2-{{ barnyard2.version }}/configure"
  tags: [ "barnyard2" ]

# - name: ln -s /usr/include/dumbnet.h /usr/include/dnet.h
#   command: ln -s /usr/include/dumbnet.h /usr/include/dnet.h
#   tags: [ "barnyard2" ]

# - name: ldconfig
#   command: ldconfig
#   tags: [ "barnyard2" ]

- name: ./configure --with-mysql --with-mysql-libraries=/usr/lib64
  command: ./configure --with-mysql --with-mysql-libraries=/usr/lib64
  args:
    chdir: "{{ barnyard2.src_dir}}/barnyard2-{{ barnyard2.version }}"
    creates: "{{ barnyard2.src_dir}}/barnyard2-{{ barnyard2.version }}/config.status"
  tags: [ "barnyard2" ]

- name: make install barnyard2
  command: "{{ item }}"
  args:
    chdir: "{{ barnyard2.src_dir}}/barnyard2-{{ barnyard2.version }}"
    creates: "/usr/local/bin/barnyard2"
  with_items:
    - 'make'
    - 'make install'
  tags: [ "barnyard2" ]

- name: Symlink /usr/local/bin/barnyard2 > /usr/sbin/barnyard2
  file:
    src: /usr/local/bin/barnyard2
    dest: /usr/sbin/barnyard2
    owner: root
    group: root
    state: link
  tags: [ "barnyard2" ]

- name: Configuring barnyard2 daemon
  template:
    src: "barnyard2.service.j2"
    dest: "/lib/systemd/system/barnyard2.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - enable barnyard2
    - restart barnyard2
  tags: [ "barnyard2" ]

- name: Generate /etc/snort/barnyard2.conf
  template:
    src: "barnyard2.conf.j2"
    dest: "/etc/snort/barnyard2.conf"
    owner: snort
    group: snort
    mode: 0644
  notify:
    - restart barnyard2
  tags: [ "barnyard2" ]
